spring.application.name=MovieBookingApplication
spring.datasource.url=jdbc:postgresql://localhost:5432/moviebookingapplication
spring.datasource.username=postgres
spring.datasource.password=Rajesh*@2000
server.servlet.session.cookie.same-site=strict
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect



# Set logging level for your application package
logging.level.com.rajesh.MovieBookingApplication=INFO

# Log output file
logging.file.name=logs/app.log

# Optional: log format
#logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} - %msg%
